### ISSUE TITLE
Lots of warnings on Flex 4.1 and compilation errors on 4.5

### ISSUE THREAD

**Issue by nicoulaj** [flex-users/flexlib#356]
Originally filed by dan.dime...@gmail.com on 2011-04-22T20:37:46

What steps will reproduce the problem?
1. Set the SDK to 4.5 (Hero)
2. Compile an app that uses flexlib
3.

What is the expected output? What do you see instead?
expected: clean compilation (ideally without deprecation warnings)
seen: had to comment out a couple of lines to make it compile in 4.5

What version of the product are you using? On what operating system?
revision 244

Please provide any additional information below.

**Comment by nicoulaj** [comment]
Closing (not relevant anymore)
